### ISSUE TITLE
Update ManagementClient exports

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.nodejs#23]
In our existing generated management client files, we only export the management client class, like this:
```typescript
// batchManagementClient.js
module.exports = BatchManagementClient;

// batchManagementClient.d.ts
declare class BatchManagement extends AzureServiceClient { ... }
export = BatchManagementClient;
```
This means that developers can only import the management client for a particular service, like this:
```typescript
import BatchManagementClient from "azure-arm-batch";
```
If they want access to the model types that are exposed by that service, then they have to do this:
```typescript
import batchManagementModels = require("../node_modules/azure-arm-batch/lib/models");
```
That's a pretty poor experience. To fix this experience, we are proposing to change the export strategy to be this:
```typescript
// batchManagementClient.js
module.exports = BatchManagementClient;
module.exports.BatchManagementModels = models;
module.exports.default = BatchManagementClient;

// batchManagementClient.d.ts
import * as models from "./models";
export default class BatchManagementClient extends AzureServiceClient { ... }
export {BatchManagementClient, models as BatchManagementModels};
```
This improves the developer experience because they can still use the same import statement as before, but they now also have the option to import like this:
```typescript
import {BatchManagementClient, BatchManagementModels} from "azure-arm-batch";
```
This is a much better experience because developers get intellisense to help them discover what is available for import from `azure-arm-batch`.

**Comment by amarzavery** [comment]
- This should close the gap for current customers developing their apps in TypeScript based on the type definitions that are shipped along with the generated node.js code.
- When we move to generating TS clients it would still be a breaking change for customers who have developed their apps in node.js. We would be exporting an object which would contain the client as one of the properties amongst other things v/s just the client that we are exporting today in the node sdk.

**Comment by daschult** [comment]
I've learned a little about ES6, Typescript, and Node.js modules/imports while working on this issue. It turns out that ES6 added support for the following:
```typescript
import BatchManagementClient from "azure-arm-batch";
```
Because ES6 added support for it, that means that all the transpilers (such as Typescript and Babel) added support for it as well. However, the way that imports/require() calls are handled in Node.js is done in such as way that it is very difficult for Node.js to support ES6 imports/modules. This means that Node.js doesn't support the import statement.
After I'm done with the work for this issue, if a customer is using Typescript or Babel to consume our packages then they can use the import statement that I showed above. However, if they are just using regular Javascript with Node.js, they'll have to change their imports from:
```javascript
var BatchManagementClient = require("azure-arm-batch");
```
to
```javascript
var BatchManagementClient = require("azure-arm-batch").BatchManagementClient;
```
or
```javascript
var batch = require("azure-arm-batch");
...
var client = new batch.BatchManagementClient(...);
```
@amarzavery How do you feel about this?

**Comment by amarzavery** [comment]
There is no point breaking customers in the current node sdk. When I prototyped this I did not have to make any changes to the way node.js works right now. However, as I mentioned above when we move to TS code gen there will for sure be a breaking change.

**Comment by amarzavery** [comment]
This line in batchManagementClient.js file still holds true
```javascript
module.exports = BatchManagementClient;
```

I simply wanted to add a patch for default so that customers developing apps in TS using the current type definition files can use 
```javascript
import BatchManagementClient from "azure-arm-batch"
```
and can keep on doing this when we move to generating the sdk using the TS Generator.

Apart from that I thought, it would be nice to export multiple things at the same time. This would make them use to the `import {A, B} from "some-package"` syntax.

**Comment by daschult** [comment]
I was writing a long message explaining the different strategies that I had attempted to make this work when I got an idea that ended up working. I'll support a pull request now.
