### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.nodejs#24]
If you run `gulp build`, `gulp regenerate`, then `npm test` some of the tests will fail.
These should be fixed or at least disabled.

**Comment by amarzavery** [comment]
Is this in autorest.nodejs or autorest.typescript ?

**Comment by daschult** [comment]
This change is happening in autorest.nodejs. That's what we talked about, right?

**Comment by daschult** [comment]
This test failure is in autorest.nodejs.
