### ISSUE TITLE
Need to make sure that mappers for paginated models have a comma (correct json)

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest.nodejs#27]
Did a fix by manually adding a comma for now
https://github.com/Azure/azure-sdk-for-node/pull/2464/commits/e1f4d978718f8c75be2aa1cab7babb44aaf6d69d
Whenever we are generating mappers for PagedModel definitions usually there are only two properties value and nextLink. However APi management has a property named count. Looks like we are not generating a correct json for paged models if we see a different property apart from value and nextLink.

/cc @RikkiGibson @daschult

**Comment by daschult** [comment]
Fixed.
